apiVersion: v1
kind: ConfigMap
metadata:
  name: chinese-config
data:
  system.yml: |
    system:
      log_level: INFO
    tts:
      compile: false
      default_speaker: Vivian
      default_bitrate: 192k
    api:
      host: 0.0.0.0
      port: 8000